[conf]
default-lang = "en"

[lang.en]
title = "A simple linguify example"
abstract = "Abstract"
test = "testing"

[lang.de]
title = "Ein einfaches Linguify Beispiel"
abstract = "Zusammenfassung"
test = "testen"

[lang.es]
title = "Un ejemplo sencillo de linguify"
abstract = "Resumen"

[lang.fr]
title = "Un exemple simple de linguify"
abstract = "résumé"


